# Generated by Django 5.2.5 on 2025-08-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtosalon', '0002_category_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='context',
            field=models.TextField(blank=True),
        ),
    ]
