# Generated by Django 5.2.4 on 2025-08-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avtosalon', '0003_car_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
